<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Test Report - {{ $user->name }}</title>
    <style>
        body {
            font-family: Arial, sans-serif;
            margin: 20px;
        }
        .header {
            text-align: center;
            margin-bottom: 30px;
        }
        .header h1 {
            margin: 0;
            font-size: 24px;
            color: #333;
        }
        .header p {
            margin: 5px 0;
            color: #666;
        }
        .section {
            margin-bottom: 25px;
        }
        .section h2 {
            font-size: 18px;
            color: #444;
            border-bottom: 2px solid #eee;
            padding-bottom: 5px;
        }
        .section table {
            width: 100%;
            border-collapse: collapse;
            margin-top: 10px;
        }
        .section table th,
        .section table td {
            border: 1px solid #ddd;
            padding: 8px;
            text-align: left;
        }
        .section table th {
            background-color: #f9f9f9;
            font-weight: bold;
        }
        .footer {
            margin-top: 30px;
            text-align: center;
            font-size: 12px;
            color: #888;
        }
    </style>
</head>
<body>
    <div class="header">
        <h1>System Test Report</h1>
        <p>Generated for: {{ $user->name }} ({{ $user->email }})</p>
        <p>Report Date: {{ $reportDate }}</p>
    </div>

    <div class="section">
        <h2>Recent Error Logs (Top 10)</h2>
        @if($errorLogs->count() > 0)
            <table>
                <thead>
                    <tr>
                        <th>ID</th>
                        <th>Message</th>
                        <th>URL</th>
                        <th>Created At</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($errorLogs as $log)
                        <tr>
                            <td>{{ $log->id }}</td>
                            <td>{{ Str::limit($log->message, 50) }}</td>
                            <td>{{ Str::limit($log->url, 30) }}</td>
                            <td>{{ $log->created_at->format('Y-m-d H:i:s') }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No error logs found.</p>
        @endif
    </div>

    <div class="section">
        <h2>Recent Activity Logs (Top 10)</h2>
        @if($activityLogs->count() > 0)
            <table>
                <thead>
                    <tr>
                        <th>User</th>
                        <th>Description</th>
                        <th>Subject</th>
                        <th>Created At</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($activityLogs as $log)
                        <tr>
                            <td>{{ $log->causer ? $log->causer->name : 'System' }}</td>
                            <td>{{ Str::limit($log->description, 40) }}</td>
                            <td>{{ $log->subject ? get_class($log->subject) . ' #' . $log->subject->id : 'N/A' }}</td>
                            <td>{{ $log->created_at->format('Y-m-d H:i:s') }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No activity logs found.</p>
        @endif
    </div>

    <div class="section">
        <h2>Recent Server Monitoring (Top 10)</h2>
        @if($monitoringLogs->count() > 0)
            <table>
                <thead>
                    <tr>
                        <th>Type</th>
                        <th>Host</th>
                        <th>Status</th>
                        <th>Last Checked</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach($monitoringLogs as $log)
                        <tr>
                            <td>{{ $log->type }}</td>
                            <td>{{ $log->host->name ?? 'Unknown' }}</td>
                            <td>{{ ucfirst($log->status) }}</td>
                            <td>{{ $log->last_ran_at->format('Y-m-d H:i:s') }}</td>
                        </tr>
                    @endforeach
                </tbody>
            </table>
        @else
            <p>No monitoring logs found.</p>
        @endif
    </div>

    <div class="footer">
        <p>Generated by {{ config('app.name') }} System Dashboard | Report generated at {{ now()->format('Y-m-d H:i:s') }}</p>
    </div>
</body>
</html>