@if(request()->ajax() || request()->has('ajax'))
    <x-tabler.form-modal title="Documentation: {{ $fileName }}" method="none">
        <div class="documentation-content p-2" id="doc-content-modal" style="max-height: 400px; overflow-y: auto;">
            {!! $htmlContent !!}
        </div>
        <div class="text-muted small mt-3 border-top pt-2">
            <div class="d-flex align-items-center">
                <svg xmlns="http://www.w3.org/2000/svg" class="icon me-2" width="16" height="16" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 8l0 4" /><path d="M12 16l0 .01" /><path d="M3 12a9 9 0 1 1 18 0a9 9 0 0 1 -18 0" /></svg>
                Last updated: {{ formatTanggalIndo($lastUpdated) }}
            </div>
        </div>
        
        <x-slot:footer>
            <x-tabler.button type="cancel" data-bs-dismiss="modal" text="Tutup" />
            <div class="d-flex gap-2 ms-auto">
                <x-tabler.button :href="route('sys.documentation.edit', $fileName)" class="btn-outline-primary" icon="ti ti-pencil" text="Edit" />
                <x-tabler.button :href="route('sys.documentation.show', $fileName)" icon="ti ti-external-link" text="View Full Page" />
            </div>
        </x-slot:footer>
    </x-tabler.form-modal>
@else
    @extends('layouts.tabler.app')

    @section('header')
        <x-tabler.page-header title="{{ $pageTitle }}" pretitle="Documentation">
            <x-slot:actions>
                <div class="btn-group">
                    <x-tabler.button type="back" :href="route('sys.documentation.index')" class="me-2" icon="ti ti-arrow-left" />
                    <x-tabler.button type="button" class="btn-outline-primary" icon="ti ti-pencil" :href="route('sys.documentation.edit', $fileName)" text="Edit" />
                </div>
            </x-slot:actions>
        </x-tabler.page-header>
    @endsection

    @section('content')
        @push('css')
            <link rel="stylesheet" href="{{ Vite::asset('resources/assets/sys/css/documentation-show.css') }}">
        @endpush

        <div class="row">
            <!-- Table of Contents - Sidebar -->
            <div class="col-lg-3">
                <div class="card sticky-top" style="top: 1rem; z-index: 100;">
                    <div class="card-header">
                        <h5 class="card-title mb-0 text-primary">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon me-2" width="20" height="20" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M4 4m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z" /><path d="M9 4v16" /><path d="M14 8v8" /><path d="M9 9h1" /><path d="M9 14h1" /><path d="M14 13h1" /><path d="M14 18h1" /></svg>
                            Table of Contents
                        </h5>
                    </div>
                    <div class="card-body p-0">
                        <nav id="toc-nav" class="nav flex-column p-2">
                            <!-- TOC will be generated by JavaScript -->
                            <div class="text-center text-muted py-4">
                                <div class="spinner-border spinner-border-sm text-muted mb-2" role="status"></div>
                                <div class="small">Loading contents...</div>
                            </div>
                        </nav>
                    </div>
                    <div class="card-footer bg-surface-secondary">
                        <div class="d-flex align-items-center">
                            <svg xmlns="http://www.w3.org/2000/svg" class="icon me-2 text-muted" width="16" height="16" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M12 8l0 4" /><path d="M12 16l0 .01" /><path d="M3 12a9 9 0 1 1 18 0a9 9 0 0 1 -18 0" /></svg>
                            <small class="text-muted">
                                Updated: {{ formatTanggalIndo($lastUpdated) }}
                            </small>
                        </div>
                    </div>
                </div>
            </div>

            <!-- Main Content -->
            <div class="col-lg-9">
                <div class="card">
                    <div class="card-body p-4 p-lg-5">
                        <div class="documentation-content" id="doc-content">
                            {!! $htmlContent !!}
                        </div>
                    </div>
                </div>

                <!-- Footer Actions -->
                <div class="mt-4 d-flex justify-content-between">
                    <x-tabler.button type="back" :href="route('sys.documentation.index')" icon="ti ti-arrow-left" text="Back to Index" />
                    <x-tabler.button type="button" class="btn-outline-primary" icon="ti ti-pencil" :href="route('sys.documentation.edit', $fileName)" text="Edit This Page" />
                </div>
            </div>
        </div>
    @endsection

    @push('scripts')
        <script>
            document.addEventListener('DOMContentLoaded', function() {
                const docContent = document.getElementById('doc-content');
                const tocNav = document.getElementById('toc-nav');

                // Generate Table of Contents from headings
                if(docContent && tocNav) {
                    const headings = Array.from(docContent.querySelectorAll('h1, h2, h3, h4'));

                    // Clear existing TOC
                    tocNav.innerHTML = '';

                    if (headings.length === 0) {
                        tocNav.innerHTML = '<div class="text-center text-muted py-3"><small>No sections found</small></div>';
                    } else {
                        // Generate TOC links
                        headings.forEach((heading, index) => {
                            const level = parseInt(heading.tagName.charAt(1));
                            const id = heading.id || 'heading-' + index;

                            // Add ID if not exists
                            if (!heading.id) {
                                heading.id = id;
                            }

                            const link = document.createElement('a');
                            link.href = '#' + id;
                            link.className = 'nav-link';
                            link.dataset.depth = level;
                            link.textContent = heading.textContent.trim();
                            link.title = heading.textContent.trim();

                            // Add click handler for smooth scroll
                            link.addEventListener('click', function(e) {
                                e.preventDefault();
                                const target = document.getElementById(id);
                                if (target) {
                                    const offset = 100; // Header offset
                                    const targetPosition = target.getBoundingClientRect().top + window.pageYOffset - offset;
                                    
                                    window.scrollTo({
                                        top: targetPosition,
                                        behavior: 'smooth'
                                    });
                                }
                            });

                            tocNav.appendChild(link);
                        });

                        // Highlight active section on scroll
                        let currentActive = null;
                        const observerOptions = {
                            root: null,
                            rootMargin: '-100px 0px -60% 0px',
                            threshold: 0
                        };

                        const observer = new IntersectionObserver((entries) => {
                            entries.forEach(entry => {
                                if (entry.isIntersecting) {
                                    const id = entry.target.id;
                                    const link = tocNav.querySelector(`a[href="#${id}"]`);

                                    if (currentActive) {
                                        currentActive.classList.remove('active');
                                    }

                                    if (link) {
                                        link.classList.add('active');
                                        currentActive = link;
                                        
                                        // Scroll TOC to keep active item visible
                                        link.scrollIntoView({
                                            behavior: 'smooth',
                                            block: 'nearest'
                                        });
                                    }
                                }
                            });
                        }, observerOptions);

                        // Observe all headings
                        headings.forEach(heading => observer.observe(heading));
                    }
                }

                // Add copy button to code blocks
                const codeBlocks = docContent.querySelectorAll('pre');
                codeBlocks.forEach(pre => {
                    const button = document.createElement('button');
                    button.className = 'btn btn-sm btn-ghost-primary position-absolute top-0 end-0 m-2';
                    button.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="16" height="16" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M8 8m0 2a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2z" /><path d="M16 8v-2a2 2 0 0 0 -2 -2h-8a2 2 0 0 0 -2 2v8a2 2 0 0 0 2 2h2" /></svg>';
                    button.title = 'Copy code';
                    button.style.cssText = 'z-index: 10;';
                    
                    pre.style.position = 'relative';
                    pre.appendChild(button);
                    
                    button.addEventListener('click', function() {
                        const code = pre.querySelector('code') || pre;
                        navigator.clipboard.writeText(code.textContent).then(() => {
                            button.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" class="icon text-success" width="16" height="16" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M5 12l5 5l10 -10" /></svg>';
                            setTimeout(() => {
                                button.innerHTML = '<svg xmlns="http://www.w3.org/2000/svg" class="icon" width="16" height="16" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round"><path stroke="none" d="M0 0h24v24H0z" fill="none"/><path d="M8 8m0 2a2 2 0 0 1 2 -2h8a2 2 0 0 1 2 2v8a2 2 0 0 1 -2 2h-8a2 2 0 0 1 -2 -2z" /><path d="M16 8v-2a2 2 0 0 0 -2 -2h-8a2 2 0 0 0 -2 2v8a2 2 0 0 0 2 2h2" /></svg>';
                            }, 2000);
                        });
                    });
                });
            });
        </script>
    @endpush
@endif
